name: ruby
version: '2.5.1'
summary: Interpreter of object-oriented scripting language Ruby
description: |
  Ruby is the interpreted scripting language for quick and easy object-oriented
  programming. It has many features to process text files and to do system
  management tasks (as in perl). It is simple, straight-forward, and extensible.
grade: stable
confinement: classic

apps:
  ruby:
    command: bin/launch $SNAP/bin/ruby
  irb:
    command: bin/launch $SNAP/bin/ruby $SNAP/bin/irb
  rdoc:
    command: bin/launch $SNAP/bin/ruby $SNAP/bin/rdoc
  ri:
    command: bin/launch $SNAP/bin/ruby $SNAP/bin/ri
  gem:
    command: bin/launch $SNAP/bin/ruby $SNAP/bin/gem
  rake:
    command: bin/launch $SNAP/bin/ruby $SNAP/bin/rake
  bundle:
    command: bin/launch $SNAP/bin/ruby $SNAP/bin/bundle

parts:
  launcher:
    plugin: dump
    source: snap/scripts
    organize: 
      "launch": bin/
  ruby:
    plugin: make
    source: https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.gz
    build-packages: [gcc, curl, autoconf, bison, libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm-dev]
    prepare: |
      echo "bundler 1.16.1 https://github.com/bundler/bundler" >> gems/bundled_gems
      curl -L -O https://rubygems.org/downloads/bundler-1.16.1.gem
      mv bundler-1.16.1.gem gems
    build: |
      ./configure --prefix=
      make
      make extract-gems
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL

