name: ruby
version: '2.5.1'
summary: Interpreter of object-oriented scripting language Ruby
description: |
  Ruby is the interpreted scripting language for quick and easy object-oriented
  programming. It has many features to process text files and to do system
  management tasks (as in perl). It is simple, straight-forward, and extensible.

grade: stable
confinement: strict

apps:
  ruby:
    command: ruby
    environment:
      RUBYLIB: $SNAP/lib/ruby/2.5.0:$SNAP/lib/ruby/2.5.0/x86_64-linux
  erb:
    command: ruby $SNAP/bin/erb
    environment:
      RUBYLIB: $SNAP/lib/ruby/2.5.0:$SNAP/lib/ruby/2.5.0/x86_64-linux
  irb:
    command: ruby $SNAP/bin/irb
    environment:
      RUBYLIB: $SNAP/lib/ruby/2.5.0:$SNAP/lib/ruby/2.5.0/x86_64-linux
  rdoc:
    command: ruby $SNAP/bin/rdoc
    environment:
      RUBYLIB: $SNAP/lib/ruby/2.5.0:$SNAP/lib/ruby/2.5.0/x86_64-linux
  ri:
    command: ruby $SNAP/bin/ri
    environment:
      RUBYLIB: $SNAP/lib/ruby/2.5.0:$SNAP/lib/ruby/2.5.0/x86_64-linux
  gem:
    command: ruby $SNAP/bin/gem
    environment:
      RUBYLIB: $SNAP/lib/ruby/2.5.0:$SNAP/lib/ruby/2.5.0/x86_64-linux
  rake:
    command: ruby $SNAP/bin/rake
    environment:
      RUBYLIB: $SNAP/lib/ruby/2.5.0:$SNAP/lib/ruby/2.5.0/x86_64-linux

parts:
  ruby:
    plugin: autotools
    source: https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.gz
    build-packages: [libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm-dev]
